name: dart_data_classes
description: An attempt at implementing data classes for Dart using the macros feature.
version: 0.1.0

environment:
  sdk: ^3.5.0-152.0.dev

dependencies:
  collection: ^1.18.0
  macros: ^0.1.0-main.5

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
